@startuml
top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User")
Person(admin, "Admin")

System(system, "Smart Home System")

System_Ext(devices, "IoT Devices", "Sensors and heating controllers")
System_Ext(PaymantService, "Paymant Service", "External paymant service")

Container_Boundary(system, "Smart Home System") {

    Container(api, "API Gateway", "Go", "Entry point for clients")

    Container(userService, "User Service", "Go", "Manages users")
    Container(telemetryService, "Telemetry Service", "Go", "Processes telemetry")
    Container(heatingService, "Heating Service", "Go", "Controls heating")
    ContainerDb(db, "PostgreSQL", "Shared DB (logically separated)")
}

Rel(user, api, "Uses")
Rel(admin, api, "Manages")

Rel(api, userService, "Call")
Rel(api, telemetryService, "Call")
Rel(api, heatingService, "Call")

Rel(userService, db, "SQL")

Rel(telemetryService, db, "SQL")
Rel(heatingService, db, "SQL")

Rel(telemetryService, devices, "HTTP")
Rel(heatingService, devices, "HTTP")
Rel(userService, PaymantService, "HTTP")

@enduml