@startuml
top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(user, "User", "A user of warmhouse system")
Person(admin, "Admin", "A staff from the company")

System(service, "Warm House Service", "Heating and monitoring system")

Rel(admin, service, "Add new devices to the system")
Rel(user, service, "Request temperature or switch on/off heating")
Rel(service, user, "Display temperature")

@enduml 